apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-crud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-crud
  template:
    metadata:
      labels:
        app: user-crud
    spec:
      containers:
      - name: my-container
        image: endmrf/user-crud:v1.1
        ports:
          - containerPort: 5000