apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        cpf TEXT UNIQUE NOT NULL,
        email VARCHAR(100) NOT NULL,
        created_at NOT NULL
    );
